### ISSUE TITLE
[Bug] Games not running from steam shortcut canberra-gtk-module Error

### ISSUE THREAD

**Issue by PeteLoveridge** [redromnon/HeroicBashLauncher#107]
After running the executable the game does not run from the Steam shortcut in Library

**To Reproduce**
1. Close steam
2. Run Bash Launcher
3. Open Steam
4. Select play in Library

Cyberpunk log:
Gtk-Message: 14:35:27.212: Failed to load module "canberra-gtk-module"
3.30.0
Using Bash Launcher v2.9.2
NOTE - This is an independent project and not affiliated with Heroic Games Launcher.

/home/deck/.local/share/Steam/steamapps/compatdata/2618968807/pfx/dosdevices/z:/home/deck/Games/Heroic/HeroicBashLauncher/GameFiles/Cyberpunk2077_Heroic.sh: line 18: flatpak: command not found
pid 34272 != 34252, skipping destruction (fork without exec?)

Loop Hero Log:
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
3.32.0
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Using Bash Launcher v2.9.2
NOTE - This is an independent project and not affiliated with Heroic Games Launcher.

ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
[cli] INFO: Logging in...
Traceback (most recent call last):
  File "legendary/cli.py", line 3054, in <module>
  File "legendary/cli.py", line 2969, in main
  File "legendary/cli.py", line 587, in launch_game
  File "legendary/core.py", line 190, in login
ValueError: No saved credentials
[4] Failed to execute script 'cli' due to unhandled exception!
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Gtk-Message: 14:35:08.822: Failed to load module "canberra-gtk-module"

** (zenity:7): WARNING **: 14:35:09.075: AT-SPI: Could not obtain desktop path or name

** (zenity:7): WARNING **: 14:35:09.094: AT-SPI: Could not obtain desktop path or name

** (zenity:7): WARNING **: 14:35:09.094: atk-bridge: get_device_events_reply: unknown signature

** (zenity:7): WARNING **: 14:35:09.094: atk-bridge: get_device_events_reply: unknown signature

** (zenity:7): WARNING **: 14:35:09.094: atk-bridge: GetRegisteredEvents returned message with unknown signature

** (zenity:7): WARNING **: 14:35:09.110: AT-SPI: Could not obtain desktop path or name

** (zenity:7): WARNING **: 14:35:09.110: atk-bridge: get_device_events_reply: unknown signature

** (zenity:7): WARNING **: 14:35:09.110: atk-bridge: get_device_events_reply: unknown signature

** (zenity:7): WARNING **: 14:35:09.110: atk-bridge: GetRegisteredEvents returned message with unknown signature
pid 6 != 2, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

**Comment by redromnon** [comment]
Did you read the Issues Section mentioned in the Bug template? Looks like you've enabled Proton compatibility for the added game script. Try disabling it.

**Comment by PeteLoveridge** [comment]
Thank you for the reply. 
How do I disable it? Sorry I'm a complete noob at this.

**Comment by PeteLoveridge** [comment]
Actually that only worked for CyberPunk Loop hero still gives me an error

**Comment by PeteLoveridge** [comment]
Heroic had decided to log me out of epic and not tell me.
