### ISSUE TITLE
[Bug] AttributeError can't run the script

### ISSUE THREAD

**Issue by adsau59** [redromnon/HeroicBashLauncher#125]
**Describe the bug**
Not running, getting attribute error, refer screenshot

logs
```
Using Bash Launcher v3.2.1
NOTE - This is an independent project and not affiliated with Heroic Games Launcher.

3.32.0
Traceback (most recent call last):
  File "func/HeroicBashLauncher.py", line 69, in <module>
  File "func/listinstalled.py", line 50, in listinstalled
  File "func/createlaunchfile.py", line 17, in createlaunchfile
AttributeError: 'Namespace' object has no attribute 'silent'
[12592] Failed to execute script 'HeroicBashLauncher' due to unhandled exception!
```

**To Reproduce**
1. Move the folder from zip to Heroic folder
2. Run the HeroicBashLauncher script

**Expected behavior**
should work

**Screenshots**
![image](https://user-images.githubusercontent.com/10076396/223505784-8b1fa3d3-c3cd-4eb6-a6f3-f8139e298118.png)

**Details**

 - Platform:  Steam Deck
 - OS: SteamOS
 - Heroic Version: 2.6.2
 - Bash Launcher Version: 3.2.1

**Additional context**

**Comment by redromnon** [comment]
Seems to be working on my side.

**Comment by redromnon** [comment]
Although I wouldn't recommend you to use the previous v3.2.0, can you please test if the error is encountered using that release?

**Comment by Xachman** [comment]
I got this as well.

**Comment by Xachman** [comment]
<img width="907" alt="image" src="https://user-images.githubusercontent.com/7697774/226337541-f19a2d4f-6a00-4f9f-8680-b82d628992e2.png">

Same issue in v3.2.0

**Comment by redromnon** [comment]
@Xachman I don't know if I've missed something or done anything stupid on my side, but I can assure you both versions - v3.2.1 & v3.2.0 work perfectly fine for me.

I'll continue to monitor this and maybe make some tweaks to the code.

I've tested v3.2.1 below.

[Screencast from 20-03-23 08:17:24 PM IST.webm](https://user-images.githubusercontent.com/74495920/226376505-9c10979e-9ea2-486d-8198-8fb30e18f7f7.webm)

**Comment by Xachman** [comment]
I was able to run it after building from source.  Had some issues after that because I installed steam with flatpak. But I think it's working aside from that.

**Comment by redromnon** [comment]
Hey,
Maybe the following build may work. Made a few changes.
https://github.com/redromnon/HeroicBashLauncher/actions/runs/4796826991
Let me know if this works @adsau59 @Xachman
