### ISSUE TITLE
[Bug] Artwork fails to download

### ISSUE THREAD

**Issue by roryabraham** [redromnon/HeroicBashLauncher#129]
**Describe the bug**
Thanks for your work on this project!

I installed Kingdom Hearts III via Heroic and was able to use v3.2.3 of this project to add it to steam and launch the game from game mode, which is awesome.

However, the artwork fails to load, with the following error:

```
File "func/artwork.py", line 72, in addartwork

FileNotFoundError: [Errno 2] No such file or directory: '/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/lib-cache/library.json'
```

**Expected behavior**
Hopefully the artwork would download and be added to steam correctly.

**Details**

 - Platform: Steam Deck
 - OS: [e.g. Ubuntu]
 - Heroic Version: 2.8.0
 - Bash Launcher Version 3.2.3

**Comment by roryabraham** [comment]
Also, all the data we're looking for appears to be in `/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/store_cache/legendary_library.json`. JSON in that file appears to have the same shape

**Comment by roryabraham** [comment]
I copied that file to `lib-cache/library.json`, and the error disappeared, but still no art unfortunately. The logs show that artwork photos were downloaded (for everything except the Logo Art), but still no dice

**Comment by redromnon** [comment]
Hey @roryabraham!

There were several changes made in Heroic v2.7.0 including this new `store_cache` path. I guess the old `lib-cache` path is now present for old Heroic users. 

While I was able to refactor Bash Launcher to support the few of new changes, I forgot to test the artwork addition feature. I won't be able to work on this anytime soon though.

**Comment by roryabraham** [comment]
Thanks for replying and for helping maintain this awesome lib @redromnon! Users can always add art manually, which is what I ended up doing. There are a bunch of youtube tutorials out there and lots of art available at https://www.steamgriddb.com/

**Comment by redromnon** [comment]
Hey @roryabraham 
Just published a new release that should fix this.

**Comment by lapastillaroja** [comment]
I'm having a similar problem running the AddToSteam.sh command
This is the error when adding Alone In The Dark 1 (with redacted user information)
```
[CRITICAL] Traceback (most recent call last):
  File "func/artwork.py", line 154, in addartwork
FileNotFoundError: [Errno 2] No such file or directory: '/home/USER/.steam/steam/userdata/USERID/config/grid/bc900962ee814d51504645df63d62efb5d515648f0278217b117d60c0b31adf2.jpg?namespace=gamesdb' -> '/home/USER/.steam/steam/userdata/USERID/config/grid/4146372959_hero.jpg'
```
Same problem happens with Indiana Jones Atlantis

**Comment by redromnon** [comment]
Hey @lapastillaroja 
I'm aware of certain bugs present since I haven't updated the project in quite some time. Try setting `"artwork" = false` in `settings.config` file, which will only add the game entry without the artwork.

You can use tools like SteamGridDB to add artwork.
