### ISSUE TITLE
App crashes parsing DLC

### ISSUE THREAD

**Issue by wsippel** [redromnon/HeroicBashLauncher#15]
On parsing installed.json, the script apparently doesn't filter out entries with 'is_dlc' set to 'true', tries to open a corresponding Heroic config which doesn't exist, and crashes:

```
Checking if Zenity is installed:
3.41.0

Cleaning left over game files if any...
[cli] INFO: Cleanup complete! Removed 0.00 MiB.


Done! Now creating launch files for your Epic Games library ...

Mendoza [1ed82fbb0d7f42db93646185e267677f]...

Traceback (most recent call last):
  File "HeroicBashLauncher.py", line 18, in <module>
  File "listinstalled.py", line 46, in listinstalled
  File "createlaunchfile.py", line 10, in createlaunchfile
  File "checkparameters.py", line 10, in checkparameters
FileNotFoundError: [Errno 2] No such file or directory: '/home/wsippel/.config/heroic/GamesConfig/1ed82fbb0d7f42db93646185e267677f.json'
[37440] Failed to execute script 'HeroicBashLauncher' due to unhandled exception!
```
'Mendoza" refers to a DLC package for Hitman 3.

**Comment by wsippel** [comment]
I added a pull request for a quick fix. Though I don't know if there are games with DLC that would require a separate launcher, so maybe we should check if 'is_dlc' is false and 'executable' is empty?

**Comment by redromnon** [comment]
Good catch there! I completely forgot about DLCs since I don't own any on Epic Games.

**Comment by redromnon** [comment]
> Added a pull request ( #16). Though I don't know if there are games with DLC that would require a separate launcher, so maybe we should check if 'is_dlc' is false and 'executable' is empty?

I'm not sure. Maybe we'll keep only 'is_dlc' to false for now.

**Comment by wsippel** [comment]
> Good catch there! I completely forgot about DLCs since I don't own any on Epic Games.
> 
> Did the program display an error dialog when it crashed?

No, it failed silently. Had to run it from a terminal to see what was going on.

**Comment by redromnon** [comment]
Oh okay.
