### ISSUE TITLE
[Bug] Unable to launch games

### ISSUE THREAD

**Issue by crusardri** [redromnon/HeroicBashLauncher#63]
### Before posting this issue, make sure you've read the [Issues section in the Readme](https://github.com/redromnon/HeroicBashLauncher#issues-and-suggestions) and the [Flatpak/Steam-Deck guide](https://github.com/redromnon/HeroicBashLauncher/wiki/Steam-Deck-(Flatpak)-Guide).

**Describe the bug**
The game don't start 

**To Reproduce**
1. Run setup.sh
2. Run game.sh

**Expected behavior**
The game runs

**Details**

- Platform: Steam Deck
- OS: SteamOS Holo 3.2
- Heroic Version: v2.3.0-beta.3 Flatpak
- Bash Launcher Version: v2.5.0 Flatpak
- Proton 7.0 | Proton-GE 7-17

**Additional context**
```

(process:4): Gtk-WARNING **: 21:38:11.439: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: 21:38:11.443: Failed to load module "canberra-gtk-module"
3.32.0


Running launch command for PREY:
STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/.steam/steam STEAM_COMPAT_DATA_PATH=/PREY /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch 52d88e9a6df248da913c8e99f1e4c526 --no-wine --wrapper "/home/deck/.steam/root/compatibilitytools.d/GE-Proton7-17/proton run" 
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching 52d88e9a6df248da913c8e99f1e4c526...
Using Bash Launcher 2.5.0

Checking if Zenity is installed:
Traceback (most recent call last):
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton7-17/proton", line 1609, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton7-17/proton", line 1403, in init_session
    g_compatdata.setup_prefix()
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton7-17/proton", line 730, in setup_prefix
    with self.prefix_lock:
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton7-17/filelock.py", line 323, in __enter__
    self.acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton7-17/filelock.py", line 271, in acquire
    self._acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton7-17/filelock.py", line 384, in _acquire
    fd = os.open(self._lock_file, open_mode)
FileNotFoundError: [Errno 2] No such file or directory: '/PREY/pfx.lock'

```

```
(process:4): Gtk-WARNING **: 21:40:20.440: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: 21:40:20.443: Failed to load module "canberra-gtk-module"
3.32.0


Running launch command for Absolute Drift:
STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/.steam/steam STEAM_COMPAT_DATA_PATH=/AbsoluteDrift /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch 19927295d6e3467887d4e830d8c85963 --no-wine --wrapper "/home/deck/.steam/root/compatibilitytools.d/Proton7.0/proton run" 
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching 19927295d6e3467887d4e830d8c85963...
Using Bash Launcher 2.5.0

Checking if Zenity is installed:
Traceback (most recent call last):
  File "/home/deck/.steam/root/compatibilitytools.d/Proton7.0/proton", line 1609, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/deck/.steam/root/compatibilitytools.d/Proton7.0/proton", line 1403, in init_session
    g_compatdata.setup_prefix()
  File "/home/deck/.steam/root/compatibilitytools.d/Proton7.0/proton", line 730, in setup_prefix
    with self.prefix_lock:
  File "/home/deck/.local/share/Steam/compatibilitytools.d/Proton 7.0/filelock.py", line 323, in __enter__
    self.acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/Proton 7.0/filelock.py", line 271, in acquire
    self._acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/Proton 7.0/filelock.py", line 384, in _acquire
    fd = os.open(self._lock_file, open_mode)
FileNotFoundError: [Errno 2] No such file or directory: '/AbsoluteDrift/pfx.lock'
```
With this one, i make a symlink to make proton works with spaces, this is a workarround of #60

**Comment by redromnon** [comment]
I thought Proton-GE would work without making any manual changes.

**Comment by thekingoflorda** [comment]
Same issue here!

**Comment by PixsaOJ** [comment]
```
Launch Command: DRI_PRIME=1 __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia PULSE_LATENCY_MSEC=60 STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/USER/.local/share/.steam/steam STEAM_COMPAT_DATA_PATH=/home/USER/Games/Heroic/Prefixes/Borderlands3 DXVK_HUD=fps WINE_FULLSCREEN_FSR=1 WINE_FULLSCREEN_FSR_STRENGTH=2 WINEESYNC=1 /usr/bin/gamemoderun /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Catnip --no-wine --wrapper "'/home/USER/.steam/steam/steamapps/common/Proton - Experimental/proton' run"

System Info:

  Heroic Version: 2.3.2 Brook
  Legendary Version:  0.20.25 Our Benefactors
  OS: ManjaroLinux KERNEL: 5.15.38-1-MANJARO ARCH: x64
  CPU: Intel Core™ i5-8300H @2.3 GOVERNOR: powersave
  RAM: Total: 15.4 GiB Available: 12.43 GiB
  GRAPHICS: GPU0: CoffeeLake-H GT2 [UHD Graphics 630]  VRAM: 512MB DRIVER:  GPU1: NVIDIA GeForce GTX 1050 Ti VRAM: 4096MB DRIVER: 510.68.02 
  PROTOCOL: x11
  

Game Settings: {
	"audioFix": true,
	"autoInstallDxvk": true,
	"autoInstallVkd3d": true,
	"enableEsync": true,
	"enableFSR": true,
	"maxSharpness": 2,
	"nvidiaPrime": true,
	"otherOptions": "",
	"savesPath": "",
	"showFps": true,
	"targetExe": "",
	"useGameMode": true,
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/home/USER/Games/Heroic/Prefixes/Borderlands3",
	"wineVersion": {
		"bin": "/home/USER/.steam/steam/steamapps/common/Proton - Experimental/proton",
		"name": "Proton - Proton - Experimental",
		"type": "proton"
	},
	"useSteamRuntime": false
}

Error Log:
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[Core] INFO: Getting ownership token.
[cli] INFO: Launching Catnip...
gamemodeauto:
Traceback (most recent call last):
  File "/home/USER/.steam/steam/steamapps/common/Proton - Experimental/proton", line 1470, in <module>
g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/USER/.steam/steam/steamapps/common/Proton - Experimental/proton", line 1272, in init_session
g_compatdata.setup_prefix()
  File "/home/USER/.steam/steam/steamapps/common/Proton - Experimental/proton", line 771, in setup_prefix
with self.prefix_lock:
  File "/home/USER/.local/share/Steam/steamapps/common/Proton - Experimental/filelock.py", line 323, in __enter__
self.acquire()
  File "/home/USER/.local/share/Steam/steamapps/common/Proton - Experimental/filelock.py", line 271, in acquire
self._acquire()
  File "/home/USER/.local/share/Steam/steamapps/common/Proton - Experimental/filelock.py", line 384, in _acquire
fd = os.open(self._lock_file, open_mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/USER/Games/Heroic/Prefixes/Borderlands3/pfx.lock'

```

**Comment by redromnon** [comment]
Looks like the wine prefix isn't created by Heroic. That's why the error - ` FileNotFoundError: [Errno 2] No such file or directory: 'path/to/prefix/pfx.lock'` exists. The fix will be released by the Heroic devs soon.

**Comment by PixsaOJ** [comment]
If it helps, I did interrupt installation once, then paused/continued it.

**Comment by redromnon** [comment]
You may try to "Verify and Repair" in the Tools section in Settings to make sure once the update is released.

**Comment by PixsaOJ** [comment]
That did not help. I changed the wine version, ran the game and switched back to Proton Experimental.

**Comment by redromnon** [comment]
Did Heroic v2.3.3 and Bash Launcher v2.6.1 solve your issue?

**Comment by MrMobss** [comment]
Yes it works perfectly, thank you.

**Comment by jcnils** [comment]
The last update solved the lock issue on Nobara Project as well (I was looking for the problem and when I found this tread I saw the update pop up). Thanks!

**Comment by redromnon** [comment]
Closing this issue as completed.

**Comment by gstacks13** [comment]
I'm still getting this same issue with every game I install.  On the latest Flatpak version of Heroic Games Launcher (2.4.0-beta as of this writing), and v2.7.5 fo Heroic Bash Launcher.  

`FileNotFoundError: [Errno 2] No such file or directory: '/path/to/game/pfx.lock'` for every game I've tried.

**Comment by TiloHeidasch** [comment]
@redromnon I do also have this problem on the steam deck. I am running Heroic 2.3.9 flatpack and HBL v2.8.0 any suggestion? Thanks!

**Comment by redromnon** [comment]
Is your game launching through Heroic directly? If it doesn't, you need to manage your Wine prefixes. Usually, the wine prefix (in the game's settings) should bw present in `~/Games/Heroic/Prefixes/GameName` and not `~/.wine`
